apiVersion: v1
kind: Secret
metadata:
  name: llm-gateway-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  SUPABASE_URL: <base64-encoded-supabase-url>
  SUPABASE_KEY: <base64-encoded-supabase-key>
  SUPABASE_SERVICE_ROLE_KEY: <base64-encoded-service-role-key>
  JWT_SECRET_KEY: <base64-encoded-jwt-secret>
  OPENAI_API_KEY: <base64-encoded-openai-key>
  ANTHROPIC_API_KEY: <base64-encoded-anthropic-key>
  GOOGLE_GEMINI_API_KEY: <base64-encoded-gemini-key>
  LANGFUSE_PUBLIC_KEY: <base64-encoded-langfuse-public-key>
  LANGFUSE_SECRET_KEY: <base64-encoded-langfuse-secret-key>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-gateway-config
data:
  HOST: "0.0.0.0"
  PORT: "8000"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://redis-service:6379/0"
  RATE_LIMIT_STORAGE: "redis"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
  RATE_LIMIT_REQUESTS_PER_HOUR: "1000"
  RETRY_ENABLED: "true"
  RETRY_MAX_ATTEMPTS: "3"
  CIRCUIT_BREAKER_ENABLED: "true"
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "60"
  PROMETHEUS_ENABLED: "true"
  BILLING_ENABLED: "true"
  BILLING_CURRENCY: "USD"
  BILLING_DEFAULT_BALANCE: "100.0" 